apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: a10-provisioner
spec:
  ttlSecondsAfterEmpty: 30
  ttlSecondsUntilExpired: 2592000
  requirements:
    - key: "karpenter.k8s.aws/instance-category"
      operator: In
      values: ["t", "m", "r"]
    - key: "karpenter.k8s.aws/instance-cpu"
      operator: In
      values: ["4", "8", "16", "32"]      
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot", "on-demand"]
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["ap-northeast-2a", "ap-northeast-2c"]   
  limits:
    resources:
      cpu: "160"
  labels:
    role: a10 
    provision: karpenter
    overprovisioning: a10    
  provider:
    subnetSelector:
      aws-ids: ${SUBNET_ID}
    securityGroupSelector:
      aws-ids: ${SECURITY_GROUP_ID}
    tags:
      Name: a10-karpenter-provision      
    blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 100Gi
        volumeType: gp3    
        deleteOnTermination: true